name: digest_auth
description: HTTP Digest Authentication for Monero's JSON-RPC API.
version: 1.0.1
repository: https://github.com/cypherstack/digest_auth

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  http: ^1.2.2 # Only needed for tests.
  # monero_rpc: ^1.0.0 # Only needed for tests.  Removed to avoid recursive dependencies.
dependencies:
  convert: ^3.1.2
  crypto: ^3.0.6
